Bug fix in libraries.py
The 'pop' function in line 58 is called wrongly, resulting in:

TypeError: 'builtin_function_or_method' object is not subscriptable